name: movie_wtc
description: credeo summer camp project 2022

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 0.0.1+1

environment:
  sdk: ">=2.17.5 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  easy_localization: ^3.0.1
  go_router: ^4.2.7
  provider: ^6.0.3
  kiwi: ^4.0.2
  smooth_page_indicator: ^1.0.0+2
  share_plus: ^4.0.10
  video_player: ^2.4.6
  flick_video_player: ^0.5.0
  image_picker: ^0.8.5+3

dev_dependencies:
  flutter_test:
    sdk: flutter

  icons_launcher: ^2.0.1
  flutter_lints: ^2.0.0

icons_launcher:
  platforms:
    android:
      enable: true
      image_path: 'assets/app_icons/app_icon_android.png'
    ios:
      enable: true
      image_path: 'assets/app_icons/app_icon_ios.png'

flutter:

  uses-material-design: true

  assets:
    - assets/localization/en.json
    - assets/icons/
    - assets/images/categories/
    - assets/images/movies/
    - assets/images/my_list/

