name: movie_wtc
description: credeo summer camp project 2022

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 0.0.1+1

environment:
  sdk: ">=2.17.5 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  easy_localization: ^3.0.1
  go_router: ^4.2.1
  provider: ^6.0.3
  kiwi: ^4.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/localization/en.json